### PR TITLE
set profiles configuration default value

### LINKED ISSUE #1: devenv new: !var: unbound variable
When I run `devenv new` I get

```
~/.devenv/libs/config.sh: line 8: !var: unbound variable
```

I'm using ZSH and OhMyZsh on Ubuntu 18.04. Bash version 4.4.19.

Do you know what's going on?

### PR DESCRIPTION
**Pull request by endorama**
This PR should fix #1, setting default values for `profiles` required configuration

### CODE REVIEW

**Comment by matjack1** [comment]
A bit better, still broken here though:

```
devenv/libexec/devenv-new: line 44: $1: unbound variable
```

**Comment by endorama** [comment]
Ok, I guess that's because the new command requires an argument.

Try passing the profile name as first argument.

**Comment by matjack1** [comment]
AH-HA

it works :)

just a bit harsh as an error message :P

**Comment by endorama** [comment]
:smile: Guess I'll add some checks on the arguments. Merging now!

**Pull request merged**
